#pragma once

class IHpManager;
class IMagazineManager;
class IPlayer;
class IGame;
class IAiManager;
class IUiManager;
class ISaveSyncManager;
class ILoadManager;
class ISaveAsyncManager;
class Item;
class Inventory;

class HpManager;
class MagazineManager;
class Player;
class Game;
class AiManager;
class UiManager;
class GameStateManager;
class DecisionManager;
class ShootingManager;
class SaveJSONManager;
class SaveTXTManager;
class LoadJSONManager;
class LoadTXTManager;
class AutoSaveManager;
class HandCuffs;
class Saw;
class CellPhone;
class Beer;
class Magnifier;
class Inverter;
class CellPhone;
class InventoryManager;
class SaveConfig;
class UiSFMLManager;

struct GameState;
struct GameConfig;