#pragma once

class IHpManager;
class IMagazineManager;
class IPlayer;
class IAiManager;
class IUiManager;
class ISaveSyncManager;
class ISaveAsyncManager;
class IAutoSaveManager;
class IInventoryManager;
class IGameStateManager;
class IDecisionManager;
class IShootingManager;
class ILoadManager;
class Item;

class HpManager;
class MagazineManager;
class Player;
class GameConsoleVersion;
class GameSFMLVersion;
class AiManager;
class UiManager;
class GameStateManager;
class DecisionManager;
class ShootingManager;
class SaveJSONManager;
class SaveTXTManager;
class LoadJSONManager;
class LoadTXTManager;
class AutoSaveManager;
class HandCuffs;
class Saw;
class Inventory;
class CellPhone;
class Beer;
class Magnifier;
class Inverter;
class InventoryManager;
class SaveConfig;
class UiSFMLManager;
class InputValidatorManager;
class IGameSFML;
class IUiSFMLManager;

struct GameState;
struct GameConfig;